/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface LoanGetByLoanNumber$Params {
  loanNumber: string;
}

export function loanGetByLoanNumber(http: HttpClient, rootUrl: string, params: LoanGetByLoanNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, loanGetByLoanNumber.PATH, 'get');
  if (params) {
    rb.path('loanNumber', params.loanNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

loanGetByLoanNumber.PATH = '/api/loans/by-number/{loanNumber}';
