/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface LoanGetAll$Params {
  customerId?: number | null;
  status?: string | null;
  isClosed?: boolean | null;
}

export function loanGetAll(http: HttpClient, rootUrl: string, params?: LoanGetAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, loanGetAll.PATH, 'get');
  if (params) {
    rb.query('customerId', params.customerId, {});
    rb.query('status', params.status, {});
    rb.query('isClosed', params.isClosed, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

loanGetAll.PATH = '/api/loans';
