/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerDocument } from '../../models/customer-document';

export interface CustomerDocumentsGetDocuments$Params {
  customerId: number;
}

export function customerDocumentsGetDocuments(http: HttpClient, rootUrl: string, params: CustomerDocumentsGetDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomerDocument>>> {
  const rb = new RequestBuilder(rootUrl, customerDocumentsGetDocuments.PATH, 'get');
  if (params) {
    rb.path('customerId', params.customerId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CustomerDocument>>;
    })
  );
}

customerDocumentsGetDocuments.PATH = '/api/customers/{customerId}/documents';
