/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ReportsLoanSummary$Params {
  branchId?: number | null;
  isClosed?: boolean | null;
  status?: string | null;
}

export function reportsLoanSummary(http: HttpClient, rootUrl: string, params?: ReportsLoanSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, reportsLoanSummary.PATH, 'get');
  if (params) {
    rb.query('branchId', params.branchId, {});
    rb.query('isClosed', params.isClosed, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

reportsLoanSummary.PATH = '/api/reports/loan-summary';
