/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ReportsCustomerLedger$Params {
  customerId: number;
  loanId?: number | null;
  fromDate?: string | null;
  toDate?: string | null;
}

export function reportsCustomerLedger(http: HttpClient, rootUrl: string, params: ReportsCustomerLedger$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, reportsCustomerLedger.PATH, 'get');
  if (params) {
    rb.path('customerId', params.customerId, {});
    rb.query('loanId', params.loanId, {});
    rb.query('fromDate', params.fromDate, {});
    rb.query('toDate', params.toDate, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

reportsCustomerLedger.PATH = '/api/reports/customer-ledger/{customerId}';
