/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DashboardSummaryDto } from '../../models/dashboard-summary-dto';

export interface ReportsDashboardSummary$Params {
  branchId?: number | null;
}

export function reportsDashboardSummary(http: HttpClient, rootUrl: string, params?: ReportsDashboardSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, reportsDashboardSummary.PATH, 'get');
  if (params) {
    rb.query('branchId', params.branchId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DashboardSummaryDto>;
    })
  );
}

reportsDashboardSummary.PATH = '/api/reports/dashboard-summary';
