/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Payment } from '../../models/payment';

export interface PaymentGetAllPayments$Params {
}

export function paymentGetAllPayments(http: HttpClient, rootUrl: string, params?: PaymentGetAllPayments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Payment>>> {
  const rb = new RequestBuilder(rootUrl, paymentGetAllPayments.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Payment>>;
    })
  );
}

paymentGetAllPayments.PATH = '/api/Payment';
