/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface CollectionGetAll$Params {
  date?: string | null;
  branchId?: number | null;
  collectorId?: string | null;
  status?: string | null;
}

export function collectionGetAll(http: HttpClient, rootUrl: string, params?: CollectionGetAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, collectionGetAll.PATH, 'get');
  if (params) {
    rb.query('date', params.date, {});
    rb.query('branchId', params.branchId, {});
    rb.query('collectorId', params.collectorId, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

collectionGetAll.PATH = '/api/collections';
