/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ActivateLicenseRequest } from './models/activate-license-request';
export type { Address } from './models/address';
export type { ApplicationUser } from './models/application-user';
export type { ApproveCollectionRequest } from './models/approve-collection-request';
export type { Branch } from './models/branch';
export type { ChangePasswordRequest } from './models/change-password-request';
export type { Collection } from './models/collection';
export type { CreateBranchRequest } from './models/create-branch-request';
export type { CreateCollectionRequest } from './models/create-collection-request';
export type { CreateCustomerRequest } from './models/create-customer-request';
export type { CreateLoanRequest } from './models/create-loan-request';
export type { CreateUserRequest } from './models/create-user-request';
export type { Customer } from './models/customer';
export type { IdentityUser } from './models/identity-user';
export type { IdentityUserOfString } from './models/identity-user-of-string';
export type { LedgerEntry } from './models/ledger-entry';
export type { Loan } from './models/loan';
export type { LoanStatus } from './models/loan-status';
export type { LoginRequest } from './models/login-request';
export type { OfFAnonymousType7OfStringAndStringAndStringAndDateTimeAndString } from './models/of-f-anonymous-type-7-of-string-and-string-and-string-and-date-time-and-string';
export type { Payment } from './models/payment';
export type { PaymentMode } from './models/payment-mode';
export type { RefreshTokenRequest } from './models/refresh-token-request';
export type { RejectCollectionRequest } from './models/reject-collection-request';
export type { RenewLicenseRequest } from './models/renew-license-request';
export type { UpdateBranchRequest } from './models/update-branch-request';
export type { UpdateCollectionRequest } from './models/update-collection-request';
export type { UpdateCustomerRequest } from './models/update-customer-request';
export type { UpdateLoanRequest } from './models/update-loan-request';
export type { UpdateUserRequest } from './models/update-user-request';
export type { VerificationStatus } from './models/verification-status';
export type { VerifyCollectionRequest } from './models/verify-collection-request';
