/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GlobalSearchResultDto } from '../../models/global-search-result-dto';

export interface SearchGlobalSearch$Params {
  q?: string;
  branchId?: number | null;
}

export function searchGlobalSearch(http: HttpClient, rootUrl: string, params?: SearchGlobalSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<GlobalSearchResultDto>> {
  const rb = new RequestBuilder(rootUrl, searchGlobalSearch.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.query('branchId', params.branchId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GlobalSearchResultDto>;
    })
  );
}

searchGlobalSearch.PATH = '/api/search';
