/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateReminderRequest } from '../../models/create-reminder-request';
import { ReminderDto } from '../../models/reminder-dto';

export interface ReminderCreateReminder$Params {
      body?: CreateReminderRequest
}

export function reminderCreateReminder(http: HttpClient, rootUrl: string, params?: ReminderCreateReminder$Params, context?: HttpContext): Observable<StrictHttpResponse<ReminderDto>> {
  const rb = new RequestBuilder(rootUrl, reminderCreateReminder.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReminderDto>;
    })
  );
}

reminderCreateReminder.PATH = '/api/reminders';
