/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReminderDto } from '../../models/reminder-dto';

export interface ReminderGetReminders$Params {
  date?: string;
}

export function reminderGetReminders(http: HttpClient, rootUrl: string, params?: ReminderGetReminders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReminderDto>>> {
  const rb = new RequestBuilder(rootUrl, reminderGetReminders.PATH, 'get');
  if (params) {
    rb.query('date', params.date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReminderDto>>;
    })
  );
}

reminderGetReminders.PATH = '/api/reminders';
