/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LookupValue } from '../../models/lookup-value';

export interface LookupsGetLookupValues$Params {
  lookupTypeId: number;
}

export function lookupsGetLookupValues(http: HttpClient, rootUrl: string, params: LookupsGetLookupValues$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LookupValue>>> {
  const rb = new RequestBuilder(rootUrl, lookupsGetLookupValues.PATH, 'get');
  if (params) {
    rb.path('lookupTypeId', params.lookupTypeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LookupValue>>;
    })
  );
}

lookupsGetLookupValues.PATH = '/api/Lookups/{lookupTypeId}';
