/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActivateLicenseRequest {
  expiryDate?: string;
  instituteName?: string;
  licenseKey?: string;
  maxBranches?: number;
  maxUsers?: number;
  startDate?: string;
}
