/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Customer } from '../models/customer';
export interface Address {
  addressId?: number;
  city: string;
  customer: Customer;
  customerId?: number;
  postalCode: string;
  state: string;
  street: string;
}
