/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Branch } from '../models/branch';
import { IdentityUser } from '../models/identity-user';
export type ApplicationUser = IdentityUser & {
'fullName': string;
'branchId'?: number | null;
'branch'?: Branch | null;
'isActive'?: boolean;
'createdAt'?: string;
'refreshToken'?: string | null;
'refreshTokenExpiry'?: string | null;
};

