/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Customer } from '../models/customer';
export interface Branch {
  branchId?: number;
  branchName: string;
  createdAt?: string;
  customers?: Array<Customer>;
  isActive?: boolean;
  place: string;
  updatedAt?: string;
}
