/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentMode } from '../models/payment-mode';
export interface CreateCollectionRequest {
  amountPaid?: number;
  collectionCode?: string;
  collectionDate?: string;
  collectorId?: string | null;
  customerId?: number;
  loanId?: number;
  paymentMode?: PaymentMode;
  remarks?: string | null;
}
