/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateReminderRequest {
  dueDate?: string;
  icon?: string;
  sub?: string;
  time?: string;
  title?: string;
  type?: string;
}
