/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserRequest {
  branchId?: number | null;
  email?: string;
  fullName?: string;
  password?: string;
  role?: string;
}
