/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCustomerRequest {
  address?: string | null;
  branchId?: number;
  customerCode?: string;
  fullName?: string;
  mobileNumber?: string;
}
