/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCustomerRequest {
  address?: string | null;
  alternateNumber?: string | null;
  branchId?: number;
  dateOfBirth?: string | null;
  fullName?: string;
  gender?: string | null;
  idProofNumber?: string | null;
  idProofType?: string | null;
  mobileNumber?: string;
  occupationType?: string | null;
}
