/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateNotificationRequest {
  linkUrl?: string | null;
  message?: string;
  title?: string;
  type?: string;
}
