/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateLoanRequest {
  customerId?: number;
  dailyDueAmount?: number;
  loanAmount?: number;
  loanNumber?: string;
  startDate?: string;
}
