/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Branch } from '../models/branch';
import { CustomerDocument } from '../models/customer-document';
import { Loan } from '../models/loan';
export interface Customer {
  address?: string | null;
  alternateNumber?: string | null;
  branch?: Branch | null;
  branchId?: number;
  createdAt?: string;
  customerId?: number;
  dateOfBirth?: string | null;
  documents?: Array<CustomerDocument>;
  fullName: string;
  gender?: string | null;
  idProofNumber?: string | null;
  idProofType?: string | null;
  isActive?: boolean;
  loans?: Array<Loan>;
  mobileNumber: string;
  occupationType?: string | null;
  updatedAt?: string;
}
