/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Customer } from '../models/customer';
export interface CustomerDocument {
  customer?: Customer | null;
  customerId?: number;
  documentPath: string;
  documentType: string;
  id?: number;
  isActive?: boolean;
  originalFileName: string;
  uploadedAt?: string;
}
