/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Branch } from '../models/branch';
import { Loan } from '../models/loan';
export interface Customer {
  address?: string | null;
  branch?: Branch | null;
  branchId?: number;
  createdAt?: string;
  customerCode: string;
  customerId?: number;
  fullName: string;
  isActive?: boolean;
  loans?: Array<Loan>;
  mobileNumber: string;
  updatedAt?: string;
}
