/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardActivityDto {
  activity?: string;
  amount?: string;
  customerId?: string;
  customerName?: string;
  date?: string;
  status?: string;
}
