/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IdentityUserOfString } from '../models/identity-user-of-string';
export type IdentityUser = IdentityUserOfString & {
};

