/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Collection } from '../models/collection';
import { Customer } from '../models/customer';
import { Loan } from '../models/loan';
export interface LedgerEntry {
  balanceAfter?: number;
  collection?: Collection | null;
  collectionId?: number;
  createdAt?: string;
  creditAmount?: number;
  customer?: Customer | null;
  customerId?: number;
  debitAmount?: number;
  entryDate?: string;
  ledgerEntryId?: number;
  loan?: Loan | null;
  loanId?: number;
}
