/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Collection } from '../models/collection';
import { Customer } from '../models/customer';
import { LedgerEntry } from '../models/ledger-entry';
import { LoanStatus } from '../models/loan-status';
export interface Loan {
  balanceAmount?: number;
  collections?: Array<Collection>;
  createdAt?: string;
  customer?: Customer | null;
  customerId?: number;
  dailyDueAmount?: number;
  expectedEndDate?: string;
  isClosed?: boolean;
  ledgerEntries?: Array<LedgerEntry>;
  loanAmount?: number;
  loanId?: number;
  loanNumber: string;
  startDate?: string;
  status?: LoanStatus;
  totalCollected?: number;
  updatedAt?: string;
}
