/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LoanStatus } from './loan-status';

/**
 * Each possible value of `LoanStatus`
 */
export const LOAN_STATUS: LoanStatus[] = [
  0,
  1,
  2
];