/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LookupValue } from '../models/lookup-value';
export interface LookupType {
  description?: string | null;
  id?: number;
  lookupValues?: Array<LookupValue>;
  name: string;
}
