/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LookupType } from '../models/lookup-type';
export interface LookupValue {
  code: string;
  displayName: string;
  id?: number;
  isActive?: boolean;
  lookupType?: LookupType | null;
  lookupTypeId?: number;
  sortOrder?: number;
}
