/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationDto {
  createdAt?: string;
  id?: string;
  isRead?: boolean;
  linkUrl?: string | null;
  message?: string;
  title?: string;
  type?: string;
}
