/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OfFAnonymousType8OfStringAndStringAndStringAndDateTimeAndString {
  environment?: string | null;
  framework?: string | null;
  os?: string | null;
  timestamp?: string;
  version?: string | null;
}
