/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Loan } from '../models/loan';
export interface Payment {
  amountPaid?: number;
  isFullPayment?: boolean;
  loan: Loan;
  loanId?: number;
  paymentDate?: string;
  paymentId?: number;
  paymentMethod: string;
}
