/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentMode } from './payment-mode';

/**
 * Each possible value of `PaymentMode`
 */
export const PAYMENT_MODE: PaymentMode[] = [
  0,
  1,
  2,
  3
];