/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReminderDto {
  dueDate?: string;
  icon?: string;
  id?: number;
  isCompleted?: boolean;
  sub?: string;
  time?: string;
  title?: string;
  type?: string;
}
