/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserRequest {
  branchId?: number | null;
  fullName?: string;
  isActive?: boolean;
  role?: string | null;
}
