/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentMode } from '../models/payment-mode';
export interface UpdateCollectionRequest {
  amountPaid?: number;
  collectionDate?: string;
  collectorId?: string | null;
  paymentMode?: PaymentMode;
  remarks?: string | null;
}
