/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCustomerRequest {
  address?: string | null;
  branchId?: number;
  fullName?: string;
  isActive?: boolean;
  mobileNumber?: string;
}
