/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  branchId?: number | null;
  branchName?: string | null;
  createdAt?: string;
  email?: string;
  fullName?: string;
  id?: string;
  isActive?: boolean;
  roles?: Array<string>;
}
