/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VerificationStatus } from './verification-status';

/**
 * Each possible value of `VerificationStatus`
 */
export const VERIFICATION_STATUS: VerificationStatus[] = [
  0,
  1,
  2,
  3
];